<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>sleet</string>
    </array>
    <key>firstLineMatch</key>
    <string>&lt;!DOCTYPE|&lt;(?i:html)|&lt;\?(?i:php)|\{\{|\{%|\{#</string>
    <key>foldingStartMarker</key>
    <string>(?x)
        (&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|li|form|dl)\b.*?&gt;
        |&lt;!--(?!.*--\s*&gt;)
        |^&lt;!--\ \#tminclude\ (?&gt;.*?--&gt;)$
        |\{%\s+(if|for|)
        )</string>
    <key>foldingStopMarker</key>
    <string>(?x)
        (&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|li|form|dl)&gt;
        |^(?!.*?&lt;!--).*?--\s*&gt;
        |^&lt;!--\ end\ tminclude\ --&gt;$
        |\{%\s+end(if|for|)
        )</string>
    <key>keyEquivalent</key>
    <string>^~V</string>
    <key>name</key>
    <string>Sleet</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>begin</key>
            <string>(&lt;)([a-zA-Z0-9:]++)(?=[^&gt;]*&gt;&lt;/\2&gt;)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.html</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(&gt;(&lt;)/)(\2)(&gt;)</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.html</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>meta.scope.between-tag-pair.html</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.html</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.html</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.tag.any.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-stuff</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>(&lt;\?)(xml)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.html</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.xml.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(\?&gt;)</string>
            <key>name</key>
            <string>meta.tag.preprocessor.xml.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-generic-attribute</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string-double-quoted</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string-single-quoted</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>&lt;!--</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>--\s*&gt;</string>
            <key>name</key>
            <string>comment.block.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>--</string>
                    <key>name</key>
                    <string>invalid.illegal.bad-comments-or-CDATA.html</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#embedded-code</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>&lt;!</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>&gt;</string>
            <key>name</key>
            <string>meta.tag.sgml.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>(DOCTYPE)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.doctype.html</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>(?=&gt;)</string>
                    <key>name</key>
                    <string>meta.tag.sgml.doctype.html</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>match</key>
                            <string>"[^"&gt;]*"</string>
                            <key>name</key>
                            <string>string.quoted.double.doctype.identifiers-and-DTDs.html</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>\[CDATA\[</string>
                    <key>end</key>
                    <string>]](?=&gt;)</string>
                    <key>name</key>
                    <string>constant.other.inline-data.html</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\s*)(?!--|&gt;)\S(\s*)</string>
                    <key>name</key>
                    <string>invalid.illegal.bad-comments-or-CDATA.html</string>
                </dict>
            </array>
        </dict>

        <dict>
            <key>include</key>
            <string>#embedded-code</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>(?:^\s+)?(&lt;)((?i:style))\b(?![^&gt;]*/&gt;)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.html</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.style.html</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(&lt;/)((?i:style))(&gt;)(?:\s*\n)?</string>
            <key>name</key>
            <string>source.css.embedded.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-stuff</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&gt;)</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.html</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>(?=&lt;/(?i:style))</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#embedded-code</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>source.css</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>(?:^\s+)?(&lt;)((?i:script))\b(?![^&gt;]*/&gt;)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.html</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.script.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=&lt;/(script|SCRIPT))(&gt;)(?:\s*\n)?</string>
            <key>endCaptures</key>
            <dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.html</string>
                </dict>
            </dict>
            <key>name</key>
            <string>source.js.embedded.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-stuff</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;!&lt;/(?:script|SCRIPT))(&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.html</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.script.html</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>(&lt;/)((?i:script))</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>captures</key>
                            <dict>
                                <key>1</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.definition.comment.js</string>
                                </dict>
                            </dict>
                            <key>match</key>
                            <string>(//).*?((?=&lt;/script)|$\n?)</string>
                            <key>name</key>
                            <string>comment.line.double-slash.js</string>
                        </dict>
                        <dict>
                            <key>begin</key>
                            <string>/\*</string>
                            <key>captures</key>
                            <dict>
                                <key>0</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.definition.comment.js</string>
                                </dict>
                            </dict>
                            <key>end</key>
                            <string>\*/|(?=&lt;/script)</string>
                            <key>name</key>
                            <string>comment.block.js</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#php</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>source.js</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>(&lt;/?)((?i:body|head|html)\b)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.html</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.structure.any.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(&gt;)</string>
            <key>name</key>
            <string>meta.tag.structure.any.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-stuff</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>(&lt;/?)((?i:address|blockquote|dd|div|dl|dt|fieldset|form|frame|frameset|h1|h2|h3|h4|h5|h6|iframe|noframes|object|ol|p|ul|applet|center|dir|hr|menu|pre)\b)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.html</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.block.any.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(&gt;)</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.html</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.tag.block.any.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-stuff</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>(&lt;/?)((?i:a|abbr|acronym|area|b|base|basefont|bdo|big|br|button|caption|cite|code|col|colgroup|del|dfn|em|font|head|html|i|img|input|ins|isindex|kbd|label|legend|li|link|map|meta|noscript|optgroup|option|param|q|s|samp|script|select|small|span|strike|strong|style|sub|sup|table|tbody|td|textarea|tfoot|th|thead|title|tr|tt|u|var)\b)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.html</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.inline.any.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>((?: ?/)?&gt;)</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.html</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.tag.inline.any.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-stuff</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>(&lt;/?)([a-zA-Z0-9:]+)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.begin.html</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.other.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(&gt;)</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.tag.end.html</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.tag.other.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-stuff</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>include</key>
            <string>#entities</string>
        </dict>
        <dict>
            <key>match</key>
            <string>&lt;&gt;</string>
            <key>name</key>
            <string>invalid.illegal.incomplete.html</string>
        </dict>
        <dict>
            <key>match</key>
            <string>&lt;</string>
            <key>name</key>
            <string>invalid.illegal.bad-angle-bracket.html</string>
        </dict>

        <!-- SLEET START -->
        <dict>
            <key>include</key>
            <string>#sleet-variable-tags</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#sleet-expression-tags</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#sleet-comment-tags</string>
        </dict>
        <!-- SLEET END -->
    </array>
    <key>repository</key>
    <dict>
        <key>embedded-code</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#ruby</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#php</string>
                </dict>

                <!-- SLEET START -->
                <dict>
                    <key>include</key>
                    <string>#sleet-variable-tags</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-expression-tags</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-comment-tags</string>
                </dict>
                <!-- SLEET END -->

                <dict>
                    <key>include</key>
                    <string>#python</string>
                </dict>
            </array>
        </dict>
        <key>entities</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.entity.html</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.entity.html</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(&amp;)([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+)(;)</string>
                    <key>name</key>
                    <string>constant.character.entity.html</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>&amp;</string>
                    <key>name</key>
                    <string>invalid.illegal.bad-ampersand.html</string>
                </dict>
            </array>
        </dict>

        <!-- SLEET START -->

        <!-- VARIABLES -->
        <key>sleet-variable-tags</key>
        <dict>
            <key>begin</key>
            <string>\{\{-?</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.tag.sleet</string>
                </dict>
            </dict>
            <key>end</key>
            <string>-?\}\}</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.tag.sleet</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.tag.template.value.sleet</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#sleet-constants</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-operators</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-functions-warg</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-functions</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-helpers</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-macros</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-objects</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-properties</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-warg</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-warg-ud</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-ud</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-strings</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-arrays</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-hashes</string>
                </dict>
            </array>
        </dict>

        <!-- EXPRESSIONS -->
        <key>sleet-expression-tags</key>
        <dict>
            <key>begin</key>
            <string>\{%-?</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.tag.sleet</string>
                </dict>
            </dict>
            <key>end</key>
            <string>-?%\}</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.tag.sleet</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.tag.template.block.sleet</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#sleet-constants</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-keywords</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-operators</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-functions-warg</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-functions</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-helpers</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-macros</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-warg</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-warg-ud</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-ud</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-objects</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-properties</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-strings</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-arrays</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-hashes</string>
                </dict>
            </array>
        </dict>

        <!-- COMMENTS -->
        <key>sleet-comment-tags</key>
        <dict>
            <key>begin</key>
            <string>\{#-?</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.begin.sleet</string>
                </dict>
            </dict>
            <key>end</key>
            <string>-?#\}</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.end.sleet</string>
                </dict>
            </dict>
            <key>name</key>
            <string>comment.block.sleet</string>
        </dict>

        <!-- CONSTANTS -->
        <key>sleet-constants</key>
        <dict>
            <key>patterns</key>
            <array>
                <!-- LANGUAGE -->
                <dict>
                    <key>match</key>
                    <string>(?i)(?&lt;=[\s\[\(\{:,])(?:true|false|null|none)(?=[\s\)\]\}\,])</string>
                    <key>name</key>
                    <string>constant.language.sleet</string>
                </dict>
                <!-- NUMERIC -->
                <dict>
                    <key>match</key>
                    <string>(?&lt;=[\s\[\(\{:,]|\.\.|\*\*)[0-9]+(?:\.[0-9]+)?(?=[\s\)\]\}\,]|\.\.|\*\*)</string>
                    <key>name</key>
                    <string>constant.numeric.sleet</string>
                </dict>
            </array>
        </dict>

        <!-- OPERATORS -->
        <key>sleet-operators</key>
        <dict>
            <key>patterns</key>
            <array>
                <!-- ARITHMETIC -->
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.operator.arithmetic.sleet</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?&lt;=\s)(\+|-|\*|/|%|//)(?=\s)</string>
                </dict>

                <!-- ASSIGNMENT -->
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.operator.assignment.sleet</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?&lt;=\s)(=|~)(?=\s)</string>
                </dict>

                <!-- BITWISE -->
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.operator.bitwise.sleet</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?&lt;=\s)(&amp;|\||\^)(?=\s)</string>
                </dict>

                <!-- COMPARISON -->
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.operator.comparison.sleet</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?&lt;=\s)((?:!|=)=|&lt;=?|&gt;=?|i(?:s|n))(?=\s)</string>
                </dict>

                <!-- LOGICAL -->
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.operator.logical.sleet</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?&lt;=\s)(not|or|and|\?|:)(?=\s)</string>
                </dict>

                <!-- (**) -->
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.operator.arithmetic.sleet</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}\]\)'"])\*\*(?=[a-zA-Z0-9_\x{7f}-\x{ff}'"])</string>
                </dict>

                <!-- (..) -->
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.operator.other.sleet</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}\]\)'"])\.\.(?=[a-zA-Z0-9_\x{7f}-\x{ff}'"])</string>
                </dict>

                <!-- (|) -->
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.operator.other.sleet</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}\]\}\)'"])\|(?=[a-zA-Z_\x{7f}-\x{ff}])</string>
                </dict>
            </array>
        </dict>

        <!-- OBJECTS -->
        <key>sleet-objects</key>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>variable.other.sleet</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;=[\s\{\[\(:,])([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)(?=[\s\}\[\]\(\)\.\|,:])</string>
        </dict>

        <!-- PROPERTIES -->
        <key>sleet-properties</key>
        <dict>
            <key>patterns</key>
            <array>
                <!-- DOT NOTATION (properties) -->
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.separator.property.sleet</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>variable.other.property.sleet</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?x)
                        (?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}])
                        (\.)([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)
                        (?=[\.\s\|\[\)\]\}:,])
                    </string>
                </dict>

                <!-- DOT NOTATION (methods) -->
                <dict>
                    <key>begin</key>
                    <string>(?x)
                        (?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}])
                        (\.)([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)
                        (\()
                    </string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.separator.property.sleet</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>variable.other.property.sleet</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.parameters.begin.sleet</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\)</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.parameters.end.sleet</string>
                        </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#sleet-constants</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#sleet-functions-warg</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#sleet-functions-warg</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#sleet-functions</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#sleet-helpers</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#sleet-macros</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#sleet-objects</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#sleet-properties</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#sleet-filters-warg</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#sleet-filters</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#sleet-filters-warg-ud</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#sleet-filters-ud</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#sleet-strings</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#sleet-arrays</string>
                        </dict>
                    </array>
                    <key>contentName</key>
                    <string>meta.function.arguments.sleet</string>
                </dict>

                <!-- ARRAY NOTATION -->
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.section.array.begin.sleet</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>variable.other.property.sleet</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.section.array.end.sleet</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.section.array.begin.sleet</string>
                        </dict>
                        <key>5</key>
                        <dict>
                            <key>name</key>
                            <string>variable.other.property.sleet</string>
                        </dict>
                        <key>6</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.section.array.end.sleet</string>
                        </dict>
                        <key>7</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.section.array.begin.sleet</string>
                        </dict>
                        <key>8</key>
                        <dict>
                            <key>name</key>
                            <string>variable.other.property.sleet</string>
                        </dict>
                        <key>9</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.section.array.end.sleet</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?x)
                        (?&lt;=[a-zA-Z0-9_\x{7f}-\x{ff}\]])
                        (?:
                            (\[)('[a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*')(\])
                            |(\[)("[a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*")(\])
                            |(\[)([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)(\])
                        )
                    </string>
                </dict>
            </array>
        </dict>

        <!-- STRINGS -->
        <key>sleet-strings</key>
        <dict>
            <key>patterns</key>
            <array>
                <!-- SINGLE QUOTED STRINGS -->
                <dict>
                    <key>begin</key>
                    <string>'</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.sleet</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>'</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.sleet</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>string.quoted.single.sleet</string>
                </dict>

                <!-- DOUBLE QUOTED STRINGS -->
                <dict>
                    <key>begin</key>
                    <string>"</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.sleet</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>"</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.sleet</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>string.quoted.double.sleet</string>
                </dict>
            </array>
        </dict>

        <!-- ARRAYS -->
        <key>sleet-arrays</key>
        <dict>
            <key>begin</key>
            <string>(?&lt;=[\s\(\{\[:,])\[</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.array.begin.sleet</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\]</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.array.end.sleet</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#sleet-arrays</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-hashes</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-constants</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-strings</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-functions-warg</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-functions</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-helpers</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-macros</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-objects</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-properties</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-warg</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-warg-ud</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-ud</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>,</string>
                    <key>name</key>
                    <string>punctuation.separator.object.sleet</string>
                </dict>
            </array>
            <key>name</key>
            <string>meta.array.sleet</string>
        </dict>

        <!-- HASHES -->
        <key>sleet-hashes</key>
        <dict>
            <key>begin</key>
            <string>(?&lt;=[\s\(\{\[:,])\{</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.hash.begin.sleet</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.hash.end.sleet</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#sleet-hashes</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-arrays</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-constants</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-strings</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-functions-warg</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-functions</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-macros</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-objects</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-properties</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-warg</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-warg-ud</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-ud</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>:</string>
                    <key>name</key>
                    <string>punctuation.separator.key-value.sleet</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>,</string>
                    <key>name</key>
                    <string>punctuation.separator.object.sleet</string>
                </dict>
            </array>
            <key>name</key>
            <string>meta.hash.sleet</string>
        </dict>

        <!-- KEYWORDS -->
        <key>sleet-keywords</key>
        <dict>
            <key>match</key>
            <string>(?&lt;=\s)((?:end)?(?:block|filter|for|foreach|while|do|switch|case|break|default|set|var|if)|as|else|elseif|extends|from|ignore missing|import|only|use|with)(?=\s)</string>
            <key>name</key>
            <string>keyword.control.sleet</string>
        </dict>

        <!-- TESTS (w/ arguments) -->
        <key>sleet-functions-warg</key>
        <dict>
            <key>begin</key>
            <string>(?&lt;=[\s\(\[\{:,])(attribute|block|constant|cycle|divisibleby|parent|range|sameas|content)(\()</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>support.function.sleet</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.begin.sleet</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.end.sleet</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#sleet-constants</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-functions-warg</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-functions-warg</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-functions</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-macros</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-objects</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-properties</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-warg</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-warg-ud</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-ud</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-strings</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-arrays</string>
                </dict>
            </array>
            <key>contentName</key>
            <string>meta.function.arguments.sleet</string>
        </dict>

        <!-- TESTS -->
        <key>sleet-functions</key>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>support.function.sleet</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;=is\s)(defined|empty|even|none|odd)</string>
        </dict>

        <!-- HELPERS (Phalcon\Tag others) -->
        <key>sleet-helpers</key>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>support.function.sleet</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(__|_t|link|style|script|meta|partial|load|get_value|reset_input|a|link_to|text_field|password_field|hidden_field|file_field|check_field|radio_field|submit_button|button|select_static|select|text_area|form|end_form|end_tag|get_title|get_meta|stylesheet_link|javascript_include|img|image|friendly_title|set_doc_type|get_doc_type)\(</string>
        </dict>

        <!-- FILTERS (w/ arguments) -->
        <key>sleet-filters-warg</key>
        <dict>
            <key>begin</key>
            <string>(?&lt;=(?:[a-zA-Z0-9_\x{7f}-\x{ff}\]\)\'\"]\|)|\{%\sfilter\s)(date|default|format|join|merge|replace)(\()</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>support.function.sleet</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.begin.sleet</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.end.sleet</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#sleet-constants</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-functions-warg</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-functions</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-helpers</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-macros</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-objects</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-properties</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-warg</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-warg-ud</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-ud</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-strings</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-arrays</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-hashes</string>
                </dict>
            </array>
            <key>contentName</key>
            <string>meta.function.arguments.sleet</string>
        </dict>

        <!-- FILTERS -->
        <key>sleet-filters</key>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>support.function.sleet</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;=(?:[a-zA-Z0-9_\x{7f}-\x{ff}\]\)\'\"]\|)|\{%\sfilter\s)(capitalize|e(?:scape)?|human|join|(?:json|url)_encode|keys|length|lower|raw|reverse|sort|striptags|title|uppercase|lowercase|nl2br|slashes)(?=[\s\|\]\}\):,]|\.\.|\*\*)</string>
        </dict>

        <!-- FILTERS (w/ arguments & user-defined) -->
        <key>sleet-filters-warg-ud</key>
        <dict>
            <key>begin</key>
            <string>(?&lt;=(?:[a-zA-Z0-9_\x{7f}-\x{ff}\]\)\'\"]\|)|\{%\sfilter\s)([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)(\()</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>meta.function-call.other.sleet</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.begin.sleet</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.end.sleet</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#sleet-constants</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-functions-warg</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-functions</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-helpers</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-macros</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-objects</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-properties</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-warg</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-warg-ud</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-filters-ud</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-strings</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-arrays</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#sleet-hashes</string>
                </dict>
            </array>
            <key>contentName</key>
            <string>meta.function.arguments.sleet</string>
        </dict>

        <!-- FILTERS (user-defined) -->
        <key>sleet-filters-ud</key>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>meta.function-call.other.sleet</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(?&lt;=(?:[a-zA-Z0-9_\x{7f}-\x{ff}\]\)\'\"]\|)|\{%\sfilter\s)([a-zA-Z_\x{7f}-\x{ff}][a-zA-Z0-9_\x{7f}-\x{ff}]*)</string>
        </dict>

        <!-- SLEET END -->

        <key>php</key>
        <dict>
            <key>begin</key>
            <string>(?=(^\s*)?&lt;\?)</string>
            <key>end</key>
            <string>(?!(^\s*)?&lt;\?)</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>source.php</string>
                </dict>
            </array>
        </dict>
        <key>string-double-quoted</key>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.html</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#embedded-code</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#entities</string>
                </dict>
            </array>
        </dict>
        <key>string-single-quoted</key>
        <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.html</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#embedded-code</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#entities</string>
                </dict>
            </array>
        </dict>
        <key>tag-generic-attribute</key>
        <dict>
            <key>match</key>
            <string>\b([a-zA-Z\-:]+)</string>
            <key>name</key>
            <string>entity.other.attribute-name.html</string>
        </dict>
        <key>tag-id-attribute</key>
        <dict>
            <key>begin</key>
            <string>\b(id)\b\s*(=)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.other.attribute-name.id.html</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.separator.key-value.html</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;='|")</string>
            <key>name</key>
            <string>meta.attribute-with-value.id.html</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>"</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.html</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>meta.toc-list.id.html</string>
                    <key>end</key>
                    <string>"</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.html</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>string.quoted.double.html</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#embedded-code</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#entities</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>'</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.html</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>meta.toc-list.id.html</string>
                    <key>end</key>
                    <string>'</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.html</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>string.quoted.single.html</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#embedded-code</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#entities</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <key>tag-stuff</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag-id-attribute</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#tag-generic-attribute</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string-double-quoted</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#string-single-quoted</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#embedded-code</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>text.html.sleet</string>
    <key>uuid</key>
    <string>b524e6a8-250b-11e2-9acd-34159e3b00de</string>
</dict>
</plist>
