<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sleet</string>
	</array>
	<key>name</key>
	<string>Sleet</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>{#</string>
			<key>comment</key>
			<string>Comment line</string>
			<key>end</key>
			<string>#}</string>
			<key>name</key>
			<string>comment.line.sleet</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{{</string>
			<key>comment</key>
			<string>Echo line</string>
			<key>end</key>
			<string>}}</string>
			<key>name</key>
			<string>variable.other.sleet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.tag.sleet</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Tag functions</string>
					<key>match</key>
					<string>\b(_t|partial|load|dump|version|get_title|get_title_separator|get_meta|text_field|password_field|hidden_field|file_field|submit_button|button|check_field|radio_field|form|text_area|image|img|link_to|a|link|script|style|meta|select|tag_html|end_tag|friendly_title|get_doc_type)\b\(</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#filters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>{%</string>
			<key>comment</key>
			<string>Control line</string>
			<key>end</key>
			<string>%}</string>
			<key>name</key>
			<string>entity.other.sleet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>PHP controls</string>
					<key>match</key>
					<string>\b((?:end)?(?:if|for|while|switch|foreach)|break|else|default|case|do|as|use|set|var|as)\b</string>
					<key>name</key>
					<string>keyword.control.sleet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#filters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Slet extends HTML</string>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)(?&lt;=[\s\[\(\{:,])(?:true|false|null)(?=[\s\)\]\}\,])</string>
					<key>name</key>
					<string>constant.language.sleet</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=[\s\[\(\{:,]|\.\.|\*\*)[0-9]+(?:\.[0-9]+)?(?=[\s\)\]\}\,]|\.\.|\*\*)</string>
					<key>name</key>
					<string>constant.numeric.sleet</string>
				</dict>
			</array>
		</dict>
		<key>filters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Filters</string>
					<key>match</key>
					<string>\|(isset|capitalize|camelize|uncamelize|human|lower|upper|alnum|alpha|email|float|int|string|strip_repeats|e|escape|strip_special|unescape|unstrip_special)\b</string>
					<key>name</key>
					<string>support.function.filter.sleet</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.arithmetic.sleet</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\s)(\+|-|\*|/|%|//)(?=\s)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.sleet</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\s)(=|~)(?=\s)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bitwise.sleet</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\s)(&amp;&amp;|\|\||\^)(?=\s)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.comparison.sleet</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\s)((?:!|=)=|&lt;=?|&gt;=?|i(?:s|n))(?=\s)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.logical.sleet</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\s)(not|or|and|\?|:)(?=\s)</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.sleet</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.sleet</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.sleet</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.sleet</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.sleet</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.sleet</string>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[A-Za-z_][A-Za-z_0-9]*</string>
					<key>name</key>
					<string>variable.other.operator.sleet</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.sleet</string>
	<key>uuid</key>
	<string>a934fe48-2452-4ea2-a46c-19135219037e</string>
</dict>
</plist>
